version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: workout_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - '6543:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
